module.exports = {
  plugins: ["@typescript-eslint", "import", "unicorn", "prettier"],
  extends: ["turbo", "plugin:@typescript-eslint/recommended", "prettier"],
  ignorePatterns: ["dist/"],
  rules: {
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/prefer-namespace-keyword": "off",
    "@typescript-eslint/no-namespace": "off",
    "import/no-unresolved": "off",
    "import/no-dynamic-require": "error",
    "import/no-absolute-path": "error",
    "import/no-self-import": "error",
    "import/no-useless-path-segments": "error",
    "import/no-unused-modules": "error",
    "import/no-extraneous-dependencies": "off",
    "import/first": "error",
    "import/no-duplicates": "error",
    "import/newline-after-import": "error",
    "import/no-deprecated": "warn",
    "import/order": ["error", { "newlines-between": "always" }],
    "unicorn/prefer-module": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-top-level-await": "error",
  },
};
